version: '3.8'
services:
  meta-imager:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - INPUT_DIR=/input
      - OUTPUT_DIR=/output
    volumes:
      - "<YOUR_INPUT_DIRECTORY>:/input"
      - "<YOUR_OUTPUT_DIRECTORY>:/output"